apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-express
  template:
    metadata:
      labels:
        app: node-express
    spec:
      containers:
        - name: node-express
          image: juniyadi/docker-example:node-express
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-express
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: node-express
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-express-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt'
spec:
  tls:
    - hosts:
        - express.k8s.juniyadi.id
      secretName: letsencrypt
  rules:
    - host: express.k8s.juniyadi.id
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: node-express
                port:
                  number: 3000
